virtual_modifiers:
  - F23
  - F24

modmap:
  - name: Global
    remap:
      CapsLock:
        alone: Esc
        held: Ctrl_L
      Muhenkan:
        alone: Muhenkan
        held: F23
      Henkan:
        alone: Henkan
        held: F24

keymap:
  - name: Global
    remap:
      F23-K: Up
      F23-H: Left
      F23-J: Down
      F23-L: Right
      F23-U: PageUp
      F23-O: PageDown
      F23-M: Enter
      F23-F: BackSpace
      F23-D: Delete
      F23-A: Home
      F23-E: End
      F23-S: Enter
      F24-H: Minus
      F24-J: Equal
      F24-K: LeftBrace
      F24-L: RightBrace
      F24-Semicolon: BackSlash
      F24-Apostrophe: Grave
      F24-Q: KEY_1
      F24-W: KEY_2
      F24-E: KEY_3
      F24-R: KEY_4
      F24-T: KEY_5
      F24-Y: KEY_6
      F24-U: KEY_7
      F24-I: KEY_8
      F24-O: KEY_9
      F24-P: KEY_0
      F23-F24-Q: F1
      F23-F24-W: F2
      F23-F24-E: F3
      F23-F24-R: F4
      F23-F24-T: F5
      F23-F24-Y: F6
      F23-F24-U: F7
      F23-F24-I: F8
      F23-F24-O: F9
      F23-F24-P: F10
      F23-F24-A: F11
      F23-F24-S: F12
